apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-pod
  name: secret-pod
  namespace: cks
spec:
  containers:
  - image: nginx
    name: secret-pod
    resources: {}
    envFrom:
      - secretRef:
          name: app-secret
      - secretRef:
          name: my-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
