apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
  namespace: cks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      volumes:
        - name: secret-vol
          secret:
            secretName: app-secret
        - name: secret-01-vol
          secret:
            secretName: secret-01
            items:
              - key: username
                path: dev-group/username
              - key: password
                path: secrets/dev-groups/passowrd
      containers:
      - image: nginx
        name: nginx
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: password
        envFrom:
          - secretRef:
              name: secret-01
        volumeMounts:
          - name: secret-vol
            mountPath: /etc/secret
          - name: secret-01-vol
            mountPath: /tmp/app-secret/

