- name: add apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: present


- name: add kube-repos
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    filename: /etc/apt/sources.list.d/kubernetes.list


- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install package
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - kubelet=1.26.0-00
      - kubeadm=1.26.0-00
      - kubectl=1.26.0-00