apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
  namespace: practise
spec:
  ports:
  - name: svc-port
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: mynginx-svc
  type: NodePort
