
apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
    - name: sidecar
      image: busybox
      args:
        - /bin/sh
        - -c tail -n+1 -f /var/log/nginx.log
      volumeMounts:
        - name: logs
          mountPath: /var/log/nginx.log
    - name: nginx
      image: nginx
      volumeMounts:
        - name: config
          mountPath: usr/share/nginx/html
        - name: logs
          mountPath: /var/log
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: pv-volume
    - name: logs
      emptyDir: {}
