podCidr: "172.16.0.0/12"

flannel:
  image:
    repository: docker.io/flannel/flannel
    tag: v0.21.5
  image_cni:
    repository: docker.io/flannel/flannel-cni-plugin
    tag: v1.1.2
  args:
  - "--ip-masq"
  - "--kube-subnet-mgr"
  backend: "vxlan"
